language: cpp

sudo: required
dist: trusty

compiler:
  - clang++
  - g++

before_install:
  - wget http://downloads.sourceforge.net/project/sbml/libsbml/5.13.0/stable/Linux/64-bit/libSBML-5.13.0-Linux-x64.deb
  - sudo dpkg -i libSBML-5.13.0-Linux-x64.deb

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make
  - ctest

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake
      - clang-3.8
      - g++-5
      - gcc-5
      - libxml2-dev
      - libbz2-dev

cache:
  directories:
    - test/integration/testsuite
    - thirdparty/googletest
